server:
  port: ${PORT:8080}

application:
  security:
    jwt:
      secret: ${tassoiturrieta2025}

spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: auth
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**
        - id: clientes
          uri: http://clientes:8080
          predicates:
            - Path=/clientes/**
        - id: ruta
          uri: http://ruta:8080
          predicates:
            - Path=/ruta/**
        - id: despacho
          uri: http://despacho:8080
          predicates:
            - Path=/despacho/**
        - id: material
          uri: http://material:8080
          predicates:
            - Path=/material/**
        - id: vehiculos
          uri: http://vehiculos:8080
          predicates:
            - Path=/vehiculos/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

logging:
  level:
    root: INFO
